before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update
  - sudo apt-get install qtbase5-dev qtmultimedia5-dev qt5-qmake qt5-default libgstreamer0.10-dev libpulse-dev libtag1-dev libtagc0-dev 

script:
  - qmake
  - make
