before_install:
  - sudo add-apt-repository ppa:kubuntu-ppa/backports -y
  - sudo apt-get update -qq
  - sudo apt-get install -y qtbase5-dev qtmultimedia5-dev qttools5-dev qt5-qmake libgstreamer1.0-dev libpulse-dev libtag1-dev libtagc0-dev 
  - sudo apt-get install qt5-default qttools5-dev-tools
script:
  - qmake
  - make

dist: trusty 
os: linux
