before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt56 
  - sudo apt-get update -qq
  - sudo apt-get install qt56-meta libgstreamer0.10-dev libpulse-dev libtag1-dev libtagc0-dev 

script:
  - qmake
  - make
