before_install:
  - sudo apt-get update -qq
  - sudo apt-get install qt56base qt56multimedia qt56tools libgstreamer1.0-dev libpulse-dev libtag1-dev libtagc0-dev 

script:
  - qmake
  - make

dist: trusty 
os: linux
