install:
  - sudo apt-add-repository ppa:ubuntu-sdk-team/ppa -y
  - sudo apt-get update
  - sudo apt-get install qtbase5-dev qt5-qmake

script:
  - pwd
  - which qmake
  - qmake
  - qmake-qt5
  - make

