# This is a basic workflow to help you get started with Actions

name: Windows Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build64:
    name: Windows 64bit Build
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2        

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0

    - name: Download GST Installer
      uses: carlosperate/download-file-action@v1.0.3
      id: download-gst
      with:
        file-url: 'https://storage.googleapis.com/okj-installer-deps/gstreamer-1.0-x86_64-1.14.4.msi'
        file-name: 'gstreamer-1.0-x86_64-1.14.4.msi'
        location: './gstdownloads'

    - name: Download GST-Dev Installer
      uses: carlosperate/download-file-action@v1.0.3
      id: download-gst-dev
      with:
        file-url: 'https://storage.googleapis.com/okj-installer-deps/gstreamer-1.0-devel-x86_64-1.14.4.msi'
        file-name: 'gstreamer-1.0-devel-x86_64-1.14.4.msi'
        location: './gstdownloads'

    - name: Install GST
      run: |
        cmd /c start /wait msiexec /package ${{ steps.download-gst.outputs.file-path }} /passive ADDLOCAL=ALL
        
    - name: Install GST-Dev
      run: |
        cmd /c start /wait msiexec /package ${{ steps.download-gst-dev.outputs.file-path }} /passive ADDLOCAL=ALL
  
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
       path: ../Qt
       key: ${{ runner.os }}-QtCache

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
       cached: ${{ steps.cache-qt.outputs.cache-hit }}
       modules: 'core gui sql network widgets multimedia concurrent svg printsupport'


    - name: Run qmake
      run: |
        mkdir build
        cd build
        call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        qmake ..
      shell: cmd

    - name: Run make
      run: |
        call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        make
        tree
      shell: cmd

    - name: Installing gcloud console tools
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCLOUD_KEY }}
        export_default_credentials: true
